self.backgroundimage = QtSvg.QSvgWidget('bottle.svg')
self.but_tempup = QtSvg.QSvgWidget('uparrow.svg', parent=self.backgroundimage)
self.but_tempup.move(240, 400)
clickable(self.but_tempup).connect(self.test)
self.but_tempdown = QtSvg.QSvgWidget('downarrow.svg', parent=self.backgroundimage)
self.but_tempdown.move(420, 400)
clickable(self.but_tempdown).connect(self.test)
self.gridLayout.addWidget(self.backgroundimage)
self.sb_flow = QLabel(parent=self.backgroundimage)
self.sb_flow.setText("40 mL/min")
self.sb_flow.move(300, 100)
self.sb_flow.setFont(font)
self.lbl_pressure = QLabel(parent=self.backgroundimage)
self.lbl_pressure.move(300, 150)
self.lbl_pressure.setText("394 bar")
self.lbl_pressure.setFont(font)
self.sb_temp = QLabel(parent=self.backgroundimage)
self.sb_temp.move(500, 400)
self.sb_temp.setText("90\N{DEGREE SIGN}")
self.sb_temp.setFont(font)
